services:
  bluesquare.storage:
    class: Bluesquare\StorageBundle\Storage
    autowire: true
    public: true
    arguments: ['user_storage']
  Bluesquare\CryptorBundle\Cryptor: '@bluesquare.storage'
